#! /bin/bash

#This is a script to  install webvo

#configuration variables
INSTALL_PATH="/var/www/"
SERVERNAME="localhost"
USERNAME="root"
USERPASS="csc4150"
DBNAME="Webvo"
XML_FILE_NAME="$INSTALL_PATH/webvo/data/info.xml"
VIDEO_PATH="/media/movies/webvo/"
CONFIG_PATH="$INSTALL_PATH/webvo/config/"
LOG_PATH="$INSTALL_PATH/webvo/logs/"
XMLTV_CONFIG="$INSTALL_PATH/webvo/config/tv_grab_na_dd.conf"
ENCODER_BIN="$INSTALL_PATH/webvo/ruby/dummy_record.rb"
FILE_PADDING="120"


#dependancy variables
packages=("apache2" "mysql-server" "ruby" "libxml-ruby" "xmltv" "libmysql-ruby")

#SERVERNAME="localhost"
#USERNAME="root"
#USERPASS="csc4150"
#DBNAME="Webvo"
config_xml_file_name="true"
config_video_path="true"
config_config_path="true"
config_log_path="true"
config_xmltv_config="true"
config_encoder_bin="true"
config_sql="false"
config_download_webvo="true"
config_apache="false"

installed_packages=""

#get configuration flags

#not sure how to do this elegantly . . .

while (( $# > 0 ))
do
	case $1 in
	"SERVERNAME:")
		SERVERNAME=$2
		shift
	;;
	"USERNAME:")
		USERNAME=$2
		shift
	;;
	"USERPASS:")
		USERPASS=$2
		shift
	;;
	"DBNAME:")
		DBNAME=$2
		shift
	;;
	"XML_FILE_NAME:")
		XML_FILE_NAME=$2
		shift
	;;
	"VIDEO_PATH:")
		VIDEO_PATH=$2
		shift
	;;
	"CONFIG_PATH:")
		CONFIG_PATH=$2
		shift
	;;
	"LOG_PATH:")
		LOG_PATH=$2root
		shift
	;;
	"XMLTV_CONFIG:")
		XMLTV_CONFIG=$2
		shift
	;;
	"ENCODER_BIN:")
		ENCODER_BIN=$2
		shift
	;;
	"FILE_PADDING:")
		FILE_PADDING=$2
		shift
	;;
	"INSTALL_PATH:")
		INSTALL_PATH=$2
		shift
	;;
	? | help | --help | -help | -?)
	cat << EOF

install_webvo [option] [value] [option] [value] ....

Options:
INSTALL_PATH:  -- where webvo should be installed default "/var/www/"
SERVERNAME:    -- the server name default "localhost"
USERNAME:      -- the mysql user name default "root"
USERPASS:      -- the mysql password default "csc4150"
DBNAME:        -- the mysql database name default "Webvo"
XML_FILE_NAME: -- the xml file name default "var/www/webvo/data/info.xml"
VIDEO_PATH:    -- the path where the recordings are saved 
                  default "/media/movies/webvo/"
CONFIG_PATH:   -- the configuration path default 
                  "$INSTALL_PATH/webvo/config/"
LOG_PATH:      -- the log path default "$INSTALL_PATH/webvo/logs/"
XMLTV_CONFIG:  -- where the xmltv settings are stored default 
                  "$INSTALL_PATH/webvo/config/tv_grab_na_dd.conf"
ENCODER_BIN:   -- where the encoder is installed default 
                  "$INSTALL_PATH/webvo/ruby/dummy_record.rb"
FILE_PADDING:  -- the file padding setting default "120"

Installs and configures WebVo the web based PVR.
For more information see http://code.google.com/p/webvo/.

EOF
exit
	;;
	*)
		echo install_webvo [option]: [value] [option] [value] ....
		echo install_webvo help
	;;
	esac
	shift
done

#check the inputs
#SERVERNAME="localhost"
#USERNAME="root"
#USERPASS="csc4150"
#DBNAME="Webvo"

#INSTALL_PATH="/var/www/"
if [ ! -d $INSTALL_PATH ]
then
	echo "$INSTALL_PATH is not a valid directory, please use an existing directory"
	exit 1
fi

if [ -d $INSTALL_PATH/webvo ]
then
	echo "Webvo directory already exists at $INSTALL_PATH"	
	echo "This could mean that Webvo is already installed"
	echo "at the install path, would you like to continue anyway?"
	echo "Enter [y]es to over-write, [n]o to install everything else,"
	echo "or [A]bort to quit installation."
	read -p "Enter [y]es, [n]o, or [a]bort: " answer
	case "$answer" in
		[yY1])
			config_download_webvo="true"			
		;;
		[nN])
			config_download_webvo="false"
		;;
		[aA0])
			exit 1
		;;
	esac
 			
fi

#VIDEO_PATH="/media/movies/webvo/"
if [ ! -d $VIDEO_PATH ]
then
	config_video_path="true"
	echo "$VIDEO_PATH either invalid or hasn't been set up yet"
fi

#CONFIG_PATH="/var/www/webvo/config/"
if [ ! -d $CONFIG_PATH ]
then
	config_config_path="true"
	echo "$CONFIG_PATH either invalid or hasn't been set up yet"
fi

#LOG_PATH="/var/www/webvo/logs/"
if [ ! -d $LOG_PATH ]
then
	config_log_path="true"
	echo "$LOG_PATH either invalid or hasn't been set up yet"
fi

#XMLTV_CONFIG="/var/www/webvo/config/tv_grab_na_dd.conf"
if [ ! -f $XMLTV_CONFIG ]
then
	config_xmltv_config="true"
	echo "$CONFIG_PATH either invalid or hasn't been set up yet"
fi

#ENCODER_BIN="/var/www/webvo/ruby/dummy_record.rb"
if [ ! -f $ENCODER_BIN ]
then
	config_encoder_bin="true"
	echo "$CONFIG_ENCODER_BIN either invalid or hasn't been set up yet"
fi

#FILE_PADDING="120"


#install required packages-------------------------------------------------------------------------
echo 'Updating apt-get'
apt-get -y -q=2 update

for package in ${packages[@]}
do
	if [ "$( dpkg --get-selections | awk 'BEGIN { FS = " "; OFS = "\t" } { $1 = $1; gsub(/\t+/, "\t"); print}' | cut -f1 | grep -x $package )" = "$NULL" ]
	then

		echo "Installing $package"
		apt-get -y install $package

		if [ $? -eq 0 ]
		then
			echo "Did not install $package"

		else
			echo "Installed $package"
			case $package in
				apache2)
					configure_apache="true"
				;;
				mysql-server)
					configure_sql="true"
				;;
			esac
		fi
	else
		echo $package already installed
	fi
done

if [ "$config_download_webvo" = "true" ]
then
	if [ -d $INSTALL_PATH ]
	then
		echo "Downloading Webvo"
		cd /tmp
		wget http://webvo.googlecode.com/files/webvo.tar.gz
		gzip -d webvo.tar.gz
		tar -xf webvo.tar
		echo "Moving Webvo to $INSTALL_PATH"
		cp -r webvo $INSTALL_PATH
		rm webvo.tar
		rm -r webvo
	else
		echo Install path $INSTALL_PATH invalid
	fi
fi
#-----------------------------------------------------------------------------------
config_sql="false"
#configue sql
if [ "$config_sql" = "true" ]
then
	#set sql root password
#	mysql -u root mysql >>EOF
#SET PASSWORD FOR 'root'@'$SERVERNAME' = PASSWORD('$USERPASS')
#quit
#EOF
	./config.rb

fi

#configure apache
echo configuring apache $config_apache
if [ "$config_apache" = "true" ]
then
	echo "Will set up apache"
	#parse some of the configuration files to set up apache
fi

echo configuring log_path
if ["$config_log_path"= "true" ]
then
	#make log path writable
	 #sudo chmod a+w logs
fi

#write out config file
echo "writing out config file $INSTALL_PATH/webvo/ruby" 
if [ -d "$INSTALL_PATH/webvo/ruby" ]
then
	if [ -f "webvo.config" ]
	then
		echo "Configuration file already exists!"
	elif [ "$config_download_webvo" = "true" ]
	then
		echo Writing Configuration File
		cd "$INSTALL_PATH/webvo/ruby"
		echo "SERVERNAME = $SERVERNAME" > webvo.config
		echo "USERNAME = $USERNAME" >> webvo.config
		echo "USERPASS = $USERPASS" >> webvo.config
		echo "DBNAME = $DBNAME" >> webvo.config
		echo "XML_FILE_NAME = $XML_FILE_NAME" >> webvo.config
		echo "VIDEO_PATH = $VIDEO_PATH" >> webvo.config
		echo "CONFIG_PATH = $CONFIG_PATH" >> webvo.config
		echo "LOG_PATH = $LOG_PATH" >> webvo.config
		echo "XMLTV_CONFIG = $XMLTV_CONFIG" >> webvo.config
		echo "ENCODER_BIN = $ENCODER_BIN" >> webvo.config
		echo "FILE_PADDING = $FILE_PADDING" >> webvo.config
	fi
fi


echo "Done with installation"

exit 0


