# Say hi to everybody
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"
puts "Hello world!"
puts "Life"